name: testing-project-task
on:
  push:
    branches:
      - main
      - "releases/**"
jobs:
  testing-project-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true
      - run: npm install
      - run: npm ci
      - run: npm test
